def build_health_response(
    user_message: str,
    symptoms=None,
    prediction=None,
    safety=None
) -> str:

    symptoms = symptoms or []
    prediction = prediction or {}
    safety = safety or {}

    # Emergency response should never be generated by the LLM.
    if safety.get("is_emergency") is True:
        return (
            "Aapke symptoms mein warning signs detect hue hain. "
            "Please urgent medical attention lein aur nearest emergency "
            "department ya local emergency service se contact karein."
        )

    condition = prediction.get("condition")
    confidence = prediction.get("confidence")

    # No prediction available.
    if not condition or confidence is None:
        if symptoms:
            symptom_text = ", ".join(symptoms[:5])
            return (
                f"Aapke bataye symptoms ({symptom_text}) ko dekhte hue "
                "abhi reliable screening result available nahi hai. "
                "Symptoms kab se hain aur kya ye worsen ho rahe hain?"
            )

        return (
            "Mujhe symptoms ko better understand karne ke liye "
            "thodi aur information chahiye. Aapko exactly kya symptoms hain?"
        )

    # Never present the model prediction as a confirmed diagnosis.
    try:
        confidence_value = float(confidence)
    except (TypeError, ValueError):
        confidence_value = None

    if confidence_value is not None:
        confidence_text = f"{confidence_value:.1f}%"
    else:
        confidence_text = "available"

    response = (
        f"Screening result mein **{condition}** ki possibility sabse zyada "
        f"aayi hai ({confidence_text}). Ye confirmed diagnosis nahi hai."
    )

    if symptoms:
        response += (
            " Aapke symptoms ko context mein dekhna important hai."
        )

    response += (
        " Agar symptoms continue, worsen, ya naye concerning symptoms "
        "develop hon, to healthcare professional se consult karein."
    )

    return response
